from enum import Enum


class GetApiV22FilmsCollectionsType(str, Enum):
    CATASTROPHE_THEME = "CATASTROPHE_THEME"
    CLOSES_RELEASES = "CLOSES_RELEASES"
    COMICS_THEME = "COMICS_THEME"
    FAMILY = "FAMILY"
    KIDS_ANIMATION_THEME = "KIDS_ANIMATION_THEME"
    LOVE_THEME = "LOVE_THEME"
    OSKAR_WINNERS_2021 = "OSKAR_WINNERS_2021"
    POPULAR_SERIES = "POPULAR_SERIES"
    TOP_250_MOVIES = "TOP_250_MOVIES"
    TOP_250_TV_SHOWS = "TOP_250_TV_SHOWS"
    TOP_POPULAR_ALL = "TOP_POPULAR_ALL"
    TOP_POPULAR_MOVIES = "TOP_POPULAR_MOVIES"
    VAMPIRE_THEME = "VAMPIRE_THEME"
    ZOMBIE_THEME = "ZOMBIE_THEME"

    def __str__(self) -> str:
        return str(self.value)
